### ISSUE TITLE
Bind the template to the logic function

### ISSUE THREAD

**Issue by djhi** [archywillhe/Template-Butler#3]
When bound to a template, the context of the logic function isn't the template.

This could be useful to apply common code to multiple template (animations for exemple)

**Comment by 0a-** [comment]
:+1: Thanks for reminder. I couldn't believe I forgot to such an important thing.

**Comment by djhi** [comment]
My pleasure, I really wanted to test this ! Thanks :)

Le Thu Jan 22 2015 at 12:35:13, Archy Wilhes <notifications@github.com> a
écrit :

**Comment by 0a-** [comment]
Glad to know it! Hope you'd like it :) My pleasure too!

**Comment by djhi** [comment]
Did you forget to release it on atmosphere ?

**Comment by 0a-** [comment]
Somehow I'm running into (this strange bug)[https://github.com/meteor/meteor/issues/3533] while trying to get it released. I'm afraid you would have to wait.

**Comment by djhi** [comment]
Ok, I'll keep an eye on atmosphere.

**Comment by 0a-** [comment]
It is up there now :)
